# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{backupify-rsolr-nokogiri}
  s.version = "0.12.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Dave Benvenuti}, %q{Ernie Makris}]
  s.date = %q{2011-08-09}
  s.description = %q{}
  s.email = %q{davebenvenuti@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "LICENSE",
    "README.rdoc",
    "VERSION",
    "lib/rsolr.rb",
    "lib/rsolr/client.rb",
    "lib/rsolr/connection.rb",
    "lib/rsolr/connection/net_http.rb",
    "lib/rsolr/connection/requestable.rb",
    "lib/rsolr/connection/utils.rb",
    "lib/rsolr/message.rb",
    "lib/rsolr/message/document.rb",
    "lib/rsolr/message/field.rb",
    "lib/rsolr/message/generator.rb"
  ]
  s.homepage = %q{http://github.com/backupify/rsolr}
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.7}
  s.summary = %q{A fork of rsolr that uses nokogiri in place of builder for xml generation}
  s.test_files = [%q{spec/api/client_spec.rb}, %q{spec/api/connection/net_http_spec.rb}, %q{spec/api/connection/requestable_spec.rb}, %q{spec/api/connection/utils_spec.rb}, %q{spec/api/message_spec.rb}, %q{spec/api/rsolr_spec.rb}, %q{spec/spec_helper.rb}, %q{Rakefile}, %q{tasks/spec.rake}, %q{tasks/rdoc.rake}]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<nokogiri>, [">= 1.3.3"])
    else
      s.add_dependency(%q<nokogiri>, [">= 1.3.3"])
    end
  else
    s.add_dependency(%q<nokogiri>, [">= 1.3.3"])
  end
end

